#!/bin/bash

# Initialize Signet node with proper directory structure
# This script sets up a complete Signet node environment

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Define paths
SIGNET_DATA_DIR="$HOME/.bitcoin/signet"
ORD_DATA_DIR="$HOME/.local/share/ord/signet"
PROJECT_DATA_DIR="$PROJECT_ROOT/signet-node"

echo "🚀 Initializing Signet Node Setup"
echo "=================================="
echo ""

# Create directory structure
echo "📁 Creating directory structure..."
mkdir -p "$SIGNET_DATA_DIR"
mkdir -p "$ORD_DATA_DIR"
mkdir -p "$PROJECT_DATA_DIR"/{wallets,backups,logs}
mkdir -p "$PROJECT_ROOT/logs"

echo "✅ Directories created"
echo ""

# Check if Bitcoin Core is installed
if ! command -v bitcoind &> /dev/null; then
    echo "❌ Bitcoin Core (bitcoind) is not installed"
    echo "Please install Bitcoin Core first: https://bitcoin.org/en/download"
    exit 1
fi

echo "✅ Bitcoin Core found: $(bitcoind --version | head -1)"

# Check if ord is installed
if ! command -v ord &> /dev/null; then
    echo "❌ ord is not installed"
    echo "Please install ord first: https://github.com/ordinals/ord"
    exit 1
fi

echo "✅ ord found: $(ord --version)"
echo ""

# Create bitcoin.conf if it doesn't exist
BITCOIN_CONF="$SIGNET_DATA_DIR/bitcoin.conf"
if [ ! -f "$BITCOIN_CONF" ]; then
    echo "📝 Creating bitcoin.conf for Signet..."
    cat > "$BITCOIN_CONF" << 'EOF'
# Bitcoin Core configuration for Signet Full Node
# Generated by signet-node-init.sh

# Network
signet=1
chain=signet

# Node settings
server=1
txindex=1
rest=1
listen=1

# Connection settings
port=38333
maxconnections=125
rpcport=38332
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

# RPC credentials
rpcuser=ordtest
rpcpassword=ordtest2024

# Performance settings
dbcache=2000
maxmempool=300
mempoolexpiry=336

# Fee settings
minrelaytxfee=0.00001
incrementalrelayfee=0.00001
fallbackfee=0.00001
discardfee=0.00001

# Index settings (required for ord)
addressindex=1
timestampindex=1
spentindex=1

# Pruning (disabled for full node)
prune=0

# Signet network peers (helps with initial sync)
addnode=23.129.64.212:38333
addnode=178.128.221.177:38333
addnode=2a01:7c8:d005:390::5:38333
addnode=v7ajjeirttkbnt32wpy3c6w3emwnfr3fkla7hpxcfokr3ysd3kqtzmqd.onion:38333

# Optional: ZMQ notifications for real-time updates
# zmqpubrawblock=tcp://127.0.0.1:28332
# zmqpubrawtx=tcp://127.0.0.1:28333
# zmqpubhashtx=tcp://127.0.0.1:28334
# zmqpubhashblock=tcp://127.0.0.1:28335

# Logging
debug=net
debug=mempool
debug=rpc
logips=1
logtimestamps=1

# Optional: Bind to specific interface
# bind=127.0.0.1:38333

# Accept incoming connections
upnp=0
discover=1
dnsseed=1
fixedseeds=1

# Wallet
wallet=ord-signet
EOF
    echo "✅ bitcoin.conf created at: $BITCOIN_CONF"
else
    echo "ℹ️  bitcoin.conf already exists at: $BITCOIN_CONF"
fi

# Update project config to use the data directory
PROJECT_CONF="$PROJECT_ROOT/configs/bitcoin-signet.conf"
echo ""
echo "📝 Updating project bitcoin config..."
cat > "$PROJECT_CONF" << EOF
# Bitcoin Core configuration for Signet
# This configuration uses the initialized Signet node

# Include the main Signet configuration
includeconf=$SIGNET_DATA_DIR/bitcoin.conf

# Override data directory to use our initialized node
datadir=$SIGNET_DATA_DIR

# Project-specific settings can be added here
EOF
echo "✅ Project config updated"

# Create a wallet initialization script
WALLET_INIT="$PROJECT_DATA_DIR/init-wallet.sh"
cat > "$WALLET_INIT" << 'EOF'
#!/bin/bash
# Initialize Bitcoin Core wallet for ord

echo "Creating Bitcoin Core wallet for ord..."
bitcoin-cli -rpcport=38332 -rpcuser=ordtest -rpcpassword=ordtest2024 \
    createwallet "ord-signet" false false "" false true
echo "✅ Wallet created"

# Generate address for funding
echo "Generating initial address..."
ADDRESS=$(bitcoin-cli -rpcport=38332 -rpcuser=ordtest -rpcpassword=ordtest2024 \
    -rpcwallet=ord-signet getnewaddress)
echo "📬 Your Signet address: $ADDRESS"
echo ""
echo "Get free Signet BTC from:"
echo "  • https://signet.bc-2.jp/"
echo "  • https://alt.signetfaucet.com/"
EOF
chmod +x "$WALLET_INIT"

echo ""
echo "🎯 Signet Node Initialization Complete!"
echo "======================================="
echo ""
echo "Data directories:"
echo "  • Bitcoin: $SIGNET_DATA_DIR"
echo "  • Ord:     $ORD_DATA_DIR"
echo "  • Project: $PROJECT_DATA_DIR"
echo ""
echo "Next steps:"
echo "  1. Start the node:     ./scripts/signet-start.sh"
echo "  2. Monitor sync:       ./scripts/signet-node-status.sh"
echo "  3. Create wallet:      $WALLET_INIT"
echo "  4. Start ord server:   ./scripts/ord-signet-start.sh"
echo ""
echo "First sync will take 30-60 minutes to download ~2GB of blockchain data."